apiVersion : apps/v1
kind: Deployment
metadata:
  name: "k8stest-e9b7"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "k8stest-e9b7"
  template:
    metadata:
      labels:
        app: "k8stest-e9b7"
    spec:
      containers:
        - name: "k8stest-e9b7"
          image: "vramakacr1.azurecr.io/k8stest"
          ports:
          - containerPort: 80