apiVersion : apps/v1
kind: Deployment
metadata:
  name: "akscluster-6ff8"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "akscluster-6ff8"
  template:
    metadata:
      labels:
        app: "akscluster-6ff8"
    spec:
      containers:
        - name: "akscluster-6ff8"
          image: "vramakacr2.azurecr.io/akscluster"
          ports:
          - containerPort: 80